### ISSUE TITLE
Keyframes are not being generated

### ISSUE THREAD

**Issue by devinhalladay** [jaobrown/tailwindcss-animation-sequencing-plugin-demo#1]
Hi! I'm trying this out on a project using tailwind version `^2.2.15`. I'm running into a strange issue:
- The plugin runs just fine. The sequenced animation class names are generated fine as well.
- It seems custom keyframes defined in `tailwindConfig.theme.extend.keyframes` are not being generated as `@keyframes` rules.

For example, here is a generated animation class:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/1934813/139753780-76ecc4ff-17e5-49ec-a497-6e0ac3bd6ca1.png">

But the keyframes are nowhere to be found, so the animation does not run. Everything works just fine if I manually define the keyframes in my `index.scss` file, but I'd prefer to keep all keyframe definitions within my tailwind config.

I've defined my keyframes as such in `tailwind.config.js`:
```
theme: {
  extend: {
    keyframes: {
      'fade-in-and-down-short': {
        from: { opacity: 0, transform: 'translateY(-1rem)' },
        to: { opacity: 1, transform: 'translateY(0)' },
    },
  },
}
```

I've taken a look through your plugin code but I am not seeing anything that would be causing the issue. Any ideas?

PS. Thank you for this library, I think once it's working for me it will be really useful!

**Comment by devinhalladay** [comment]
I was thinking maybe the newer versions of Tailwind are purging the unused keyframes (since they are not explicitly defined in tailwind.config.js) but [their docs say this is not the default](https://tailwindcss.com/docs/optimizing-for-production#removing-unused-keyframes)…hm…


If I add:
```
animation: {
  'fade-in-and-down-short': 'fade-in-and-down-short 0.3s ease-in-out'
},
```

everything works as expected. I'm gonna do some more digging

**Comment by devinhalladay** [comment]
Confirmed this works on tailwind version `2.1.1` when I downgraded as per this repo's package.json.

**Comment by jaobrown** [comment]
@devinhalladay I'm sorry this is giving you issues!

To be honest, I won't have time to dive into this for a couple of weeks—traveling and starting a new role, so I am pre-occupied. 

I hope that the plugin is parsable enough that you are able to resolve the issue. If you do happen to solve it, I'd love to hear what the issue/solve ends up being. 

I will do my best to come back to this when I do have time, if I don't see anything from you before then. 

Best of luck! 🙂

**Comment by devinhalladay** [comment]
No problem, good luck with your new role! I'll share an update if I manage to fix it. For now, it works fine if I add a key to the animation config which matches my keyframe names.

**Comment by reqyo** [comment]
@devinhalladay did you ever manage to fix this? Trying to use it in version 3 of my astro project, getting the same as you described.

**Comment by jaobrown** [comment]
@reqyo apologies for missing this—did you ever solve this? If not, what version of tailwind are you using? Happy to take another look into this–this was written a good while ago (maybe even before JIT), so highly likely something just needs reworked to handle changes.

**Comment by reqyo** [comment]
Hey @jaobrown, sorry mate been busy with work. I did in fact fix it, it was something with it being excluded at build time but I can't for the life of me remember what I did. Probably something to do with JIT maybe.
